# Generated by Django 5.2.13 on 2026-04-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('name', models.CharField(max_length=255, verbose_name='Название университета')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/', verbose_name='Логотип')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='universities/covers/', verbose_name='Обложка')),
                ('description_markdown', models.TextField(blank=True, verbose_name='Описание Markdown')),
                ('university_type', models.CharField(choices=[('state', 'Государственный'), ('private', 'Частный'), ('other', 'Другое')], default='state', max_length=50, verbose_name='Тип университета')),
                ('partner_status', models.BooleanField(default=False, verbose_name='Партнёр Student’s Life')),
                ('recognized_status', models.BooleanField(default=False, verbose_name='Признаваемый вуз')),
                ('official_website', models.URLField(blank=True, verbose_name='Официальный сайт')),
                ('languages', models.CharField(blank=True, max_length=255, verbose_name='Языки обучения')),
                ('education_levels', models.CharField(blank=True, max_length=255, verbose_name='Уровни обучения')),
                ('has_dormitory', models.BooleanField(default=False, verbose_name='Есть общежитие')),
                ('dormitory_cost', models.CharField(blank=True, max_length=255, verbose_name='Стоимость общежития')),
                ('scholarship_available', models.BooleanField(default=False, verbose_name='Есть стипендии')),
                ('tuition_from', models.CharField(blank=True, max_length=255, verbose_name='Стоимость обучения от')),
                ('application_deadline', models.CharField(blank=True, max_length=255, verbose_name='Сроки подачи')),
                ('required_documents', models.TextField(blank=True, verbose_name='Необходимые документы')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='locations.city', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='locations.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=255, verbose_name='Название программы')),
                ('level', models.CharField(choices=[('foundation', 'Подкурс / Foundation'), ('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('phd', 'Аспирантура / PhD'), ('language', 'Языковые курсы'), ('other', 'Другое')], max_length=50, verbose_name='Уровень')),
                ('faculty', models.CharField(blank=True, max_length=255, verbose_name='Факультет')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='Специальность')),
                ('language', models.CharField(blank=True, max_length=100, verbose_name='Язык обучения')),
                ('duration', models.CharField(blank=True, max_length=100, verbose_name='Срок обучения')),
                ('tuition_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость обучения')),
                ('currency', models.CharField(default='USD', max_length=20, verbose_name='Валюта')),
                ('application_deadline', models.CharField(blank=True, max_length=255, verbose_name='Дедлайн подачи')),
                ('start_date', models.CharField(blank=True, max_length=255, verbose_name='Начало обучения')),
                ('required_documents', models.TextField(blank=True, verbose_name='Необходимые документы')),
                ('requirements', models.TextField(blank=True, verbose_name='Требования')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='universities.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': 'Программы обучения',
                'ordering': ['university__name', 'sort_order', 'title'],
            },
        ),
    ]
