QUESTIONNAIRE_FIELD_LABELS = {
    'form_type': 'Тип заявки',
    'status': 'Статус анкеты',
    'full_name': 'Полное ФИО',
    'birth_date': 'Дата рождения',
    'gender': 'Пол',
    'citizenship': 'Гражданство',
    'marital_status': 'Семейное положение',
    'face_photo': 'Фотография лица',
    'residence_country': 'Страна проживания',
    'residence_region': 'Область / регион',
    'residence_city': 'Город / населенный пункт',
    'residence_street': 'Улица',
    'residence_house': 'Дом / квартира',
    'residence_postal_code': 'Почтовый индекс',
    'passport_number': 'Паспорт серия и номер',
    'passport_issued_by': 'Где оформлен паспорт',
    'passport_issue_date': 'Дата начала действия паспорта',
    'passport_expiry_date': 'Дата окончания действия паспорта',
    'phone': 'Основной номер телефона',
    'email': 'Email',
    'extra_phone': 'Дополнительный номер телефона',
    'imo': 'Imo',
    'telegram': 'Telegram',
    'preferred_contact_method': 'Предпочтительный способ связи',
    'parent_full_name': 'ФИО родителя',
    'parent_relation': 'Кем является родитель',
    'parent_contacts': 'Контакты родителя',
    'parent_workplace': 'Кем и где работает родитель',
    'family_members': 'Состав семьи',
    'education_level': 'Уровень образования',
    'school_class': 'Класс',
    'school_name': 'Учебное заведение',
    'school_country': 'Страна учебного заведения',
    'school_city': 'Город учебного заведения',
    'graduation_year': 'Год окончания',
    'education_status': 'Текущий статус образования',
    'achievements': 'Достижения',
    'languages': 'Языки',
    'desired_program': 'Желаемая программа / вуз',
    'admission_goal': 'Цель поступления',
    'desired_city': 'Желаемый город поступления',
    'desired_country': 'Желаемая страна поступления',
    'desired_language': 'Желаемый язык обучения',
    'desired_education_level': 'Желаемый уровень обучения',
    'admission_urgency': 'Срочность поступления',
    'help_needed': 'Нужна помощь с',
    'has_visa': 'Виза имеется или нет',
    'visa_country': 'Страна оформления визы',
    'visa_city': 'Город оформления визы',
    'visa_valid_until': 'Срок действия визы',
    'has_international_passport': 'Есть действующий загранпаспорт',
    'hobbies': 'Любимые хобби',
    'applicant_comment': 'Дополнительный комментарий',
    'referral_source': 'Откуда узнали о Student’s Life',
    'data_processing_consent': 'Согласие на обработку персональных данных',
    'submitted_at': 'Дата отправки анкеты',
    'generated_document_at': 'Дата формирования документа',
}


def questionnaire_field_label(field_name):
    return QUESTIONNAIRE_FIELD_LABELS.get(field_name, field_name)


def questionnaire_field_labels(field_names):
    return [questionnaire_field_label(field_name) for field_name in field_names]
