# Generated by Django 5.2.13 on 2026-07-07 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('exam_date', models.DateField(verbose_name='Exam date')),
                ('exam_time', models.TimeField(verbose_name='Exam time')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='Timezone')),
                ('comment', models.TextField(blank=True, verbose_name='Manager comment')),
                ('reminder_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Reminder start at')),
                ('repeat_until_acknowledged', models.BooleanField(default=True, verbose_name='Repeat until acknowledged')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledged at')),
                ('acknowledged_by_user', models.BooleanField(default=False, verbose_name='Acknowledged by user')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('manager_sl_exam_id', models.CharField(blank=True, max_length=100, verbose_name='Manager SL exam ID')),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='Last reminded at')),
                ('next_reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Next reminder at')),
                ('created_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_exams', to=settings.AUTH_USER_MODEL, verbose_name='Created by manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_exams', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Client exam',
                'verbose_name_plural': 'Client exams',
                'ordering': ['exam_date', 'exam_time', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', 'exam_date'], name='notificatio_user_id_78fdc2_idx'), models.Index(fields=['acknowledged_by_user', 'next_reminder_at'], name='notificatio_acknowl_5c5de9_idx')],
            },
        ),
    ]
