# Generated by Django 5.0.8 on 2026-07-08 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_clientexam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(default='Напоминание об экзамене', max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Текст уведомления')),
                ('remind_at', models.DateTimeField(verbose_name='Дата и время уведомления')),
                ('timezone', models.CharField(default='Asia/Ashgabat', max_length=64, verbose_name='Часовой пояс')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('cancelled', 'Отменено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_reminders', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Напоминание менеджера',
                'verbose_name_plural': 'Календарь напоминаний',
                'ordering': ['-remind_at'],
                'indexes': [models.Index(fields=['owner', 'status', 'remind_at'], name='notificatio_owner_i_85a419_idx'), models.Index(fields=['status', 'remind_at'], name='notificatio_status_881073_idx')],
            },
        ),
    ]
