# Generated by Django 5.0.8 on 2026-07-10 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_adminreminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientexam',
            options={'ordering': ['exam_date', 'exam_time', '-created_at'], 'verbose_name': 'Экзамен клиента', 'verbose_name_plural': 'Экзамены клиентов'},
        ),
        migrations.AddField(
            model_name='clientexam',
            name='target_devices',
            field=models.ManyToManyField(blank=True, help_text='Если выбрать устройства, push уйдёт только на них. Если оставить пустым, push уйдёт на все активные устройства пользователя.', related_name='client_exams', to='notifications.devicetoken', verbose_name='Устройства для push'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='acknowledged_by_user',
            field=models.BooleanField(default=False, verbose_name='Пользователь подтвердил'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='created_by_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_exams', to=settings.AUTH_USER_MODEL, verbose_name='Создал менеджер'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='exam_date',
            field=models.DateField(verbose_name='Дата экзамена'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='exam_time',
            field=models.TimeField(verbose_name='Время экзамена'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='next_reminder_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующее напоминание'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='reminder_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начать напоминать с'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='repeat_until_acknowledged',
            field=models.BooleanField(default=True, verbose_name='Повторять до подтверждения'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Предмет экзамена'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='timezone',
            field=models.CharField(default='Asia/Ashgabat', max_length=64, verbose_name='Часовой пояс'),
        ),
        migrations.AlterField(
            model_name='clientexam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_exams', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
