# Generated by Django 5.2.13 on 2026-04-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('description_markdown', models.TextField(blank=True, verbose_name='Полное описание Markdown')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Иконка')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/covers/', verbose_name='Обложка')),
                ('required_documents', models.TextField(blank=True, verbose_name='Необходимые документы')),
                ('estimated_time', models.CharField(blank=True, max_length=255, verbose_name='Примерные сроки')),
                ('button_text', models.CharField(default='Подать заявку', max_length=100, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
