# Generated by Django 5.2.13 on 2026-04-28 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Страна проживания')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город проживания')),
                ('citizenship', models.CharField(blank=True, max_length=255, verbose_name='Гражданство')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Аватар')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык приложения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Профили клиентов',
            },
        ),
    ]
