# Generated by Django 5.2.13 on 2026-04-28 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('manager_assigned', 'Назначен менеджер'), ('consultation', 'На консультации'), ('waiting_documents', 'Ожидаются документы'), ('documents_received', 'Документы получены'), ('in_progress', 'В работе'), ('sent_to_university', 'Отправлено в университет'), ('waiting_response', 'Ожидается ответ'), ('approved', 'Одобрено'), ('rejected', 'Отказ'), ('completed', 'Завершено'), ('closed', 'Закрыто')], default='new', max_length=50, verbose_name='Статус')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('citizenship', models.CharField(blank=True, max_length=255, verbose_name='Гражданство')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Страна проживания')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Город проживания')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Телефон'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], default='whatsapp', max_length=50, verbose_name='Предпочтительный способ связи')),
                ('education_level', models.CharField(blank=True, max_length=255, verbose_name='Уровень образования')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='Специальность')),
                ('study_language', models.CharField(blank=True, max_length=100, verbose_name='Язык обучения')),
                ('start_year', models.CharField(blank=True, max_length=20, verbose_name='Год начала обучения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('source', models.CharField(default='mobile_app', max_length=100, verbose_name='Источник заявки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_platform', models.CharField(blank=True, max_length=100, verbose_name='Платформа устройства')),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='staff.staffprofile', verbose_name='Ответственный менеджер')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='services.service', verbose_name='Услуга')),
                ('target_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_applications', to='locations.city', verbose_name='Желаемый город')),
                ('target_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_applications', to='locations.country', verbose_name='Желаемая страна')),
                ('target_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='universities.program', verbose_name='Желаемая программа')),
                ('target_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='universities.university', verbose_name='Желаемый университет')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(upload_to='applications/files/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('passport', 'Паспорт'), ('certificate', 'Аттестат'), ('diploma', 'Диплом'), ('transcript', 'Приложение / Transcript'), ('photo', 'Фото'), ('medical', 'Медицинская справка'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Тип файла')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Оригинальное имя файла')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='applications.application', verbose_name='Заявка')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем загружен')),
            ],
            options={
                'verbose_name': 'Файл заявки',
                'verbose_name_plural': 'Файлы заявок',
                'ordering': ['-created_at'],
            },
        ),
    ]
