# Generated by Codex on 2026-06-16

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_manager_sl_sync_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationfile',
            name='file',
            field=models.FileField(upload_to=apps.applications.models.application_file_upload_to, verbose_name='Файл'),
        ),
    ]
