# Generated by Django 5.1.15 on 2026-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='reviewed_by_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email проверившего'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='reviewed_by_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя проверившего'),
        ),
    ]
