# Generated by Codex on 2026-06-16

import apps.chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.ImageField(upload_to=apps.chat.models.chat_image_upload_to, verbose_name='Изображение')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content-Type')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер, байт')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение чата',
                'verbose_name_plural': 'Вложения чата',
                'ordering': ['created_at'],
            },
        ),
    ]
