# Generated by Django 5.2.13 on 2026-04-28 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('name', models.CharField(max_length=255, verbose_name='Название страны')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='countries/flags/', verbose_name='Флаг')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='countries/covers/', verbose_name='Обложка')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('description_markdown', models.TextField(blank=True, verbose_name='Описание Markdown')),
                ('visa_info', models.TextField(blank=True, verbose_name='Информация о визе')),
                ('work_info', models.TextField(blank=True, verbose_name='Работа во время учёбы')),
                ('average_tuition', models.CharField(blank=True, max_length=255, verbose_name='Средняя стоимость обучения')),
                ('average_living_cost', models.CharField(blank=True, max_length=255, verbose_name='Средняя стоимость жизни')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, verbose_name='SEO описание')),
                ('name', models.CharField(max_length=255, verbose_name='Название города')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/', verbose_name='Фото города')),
                ('description_markdown', models.TextField(blank=True, verbose_name='Описание Markdown')),
                ('rent_cost', models.CharField(blank=True, max_length=255, verbose_name='Аренда / жильё')),
                ('food_cost', models.CharField(blank=True, max_length=255, verbose_name='Питание')),
                ('transport_cost', models.CharField(blank=True, max_length=255, verbose_name='Транспорт')),
                ('total_monthly_cost', models.CharField(blank=True, max_length=255, verbose_name='Итого в месяц')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='locations.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['country__name', 'sort_order', 'name'],
                'unique_together': {('country', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('title', models.CharField(max_length=255, verbose_name='Название офиса')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('whatsapp', models.CharField(blank=True, max_length=100, verbose_name='WhatsApp')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('imo', models.CharField(blank=True, max_length=100, verbose_name='IMO')),
                ('work_time', models.CharField(blank=True, max_length=255, verbose_name='Время работы')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offices/', verbose_name='Фото офиса')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='locations.city', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offices', to='locations.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Офис',
                'verbose_name_plural': 'Офисы',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
